---
title: "Gov 50 Final Project"
author: "Erica Ho"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---


## Project thoughts

I am interested in exploring data related to repression indexes in Singapore. I am taking a class on authoritarianism where I am tasked with conducting a study on Lee Kuan Yew's dictatorship and repression styles. There are several ways to measure repression, such as V-Dem, Polity, or via a binary scale. I would like to compile this data and display it visually using R. 

## Proposal 

Does incumbency impact a republican representative's likelihood of outwardly denying the 2020 Election results? In this study, I plan determine if there is a correlation between the incumbency of congressional republican representatives and if they deny the 2020 election. I hypothesis that being an incumbent increases the candidates feelings of job security, and are thus more likely to express potentially polarizing view points, such as denying the election. Thus, I expect to find a positive correlation between incumbency on the congressional candidate and election denial. 

To evaluate this data, I plan to filter the data by office to ensure that I am only evaluating candidates for the house of representative. I will also filter by party because only republican candidates denied the election. Eliminating democrats from this study allows me to observe a more specific and relevant portion of the data. I will then ensure that the numbers of representatives from each state are proportionately represented. Lastly, I plot the data to determine if the proportion of incumbents who deny the election is greater than the proportion of non-incumbents who don't outwardly deny the election.

```{r}
library(ggplot2)
library(tidyverse)
election_deniers_data <- read_csv("fivethirtyeight_election_deniers.csv")

e2 <- election_deniers_data |>
  filter(Office == "Representative")|>
  ##mutate(definitive_stance = if_else(Stance == "Fully accepted", 1, 0))|>
  mutate(definitive_stance = case_when(Stance = "Fully accepted" ~ 1,
                                        Stance = "Fully denied" ~ 1,
                                        Stance = "Accepted with reservations" ~ 0,
                                        Stance = "Accepted with reservations" ~ 0))
## I want to create a "Definitive Stance variable" that I can calculate. How do I convert my categorical variables (Fully Accepted, Fully Denied") to 1, and the others to zero?
## later on, how to I control geography? Do i have to worry about that now or can I list it as a limitation?
e2
```


